name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests 
      - name: Artifacts
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
      - uses: actions/upload-artifact@v2
          if: failure()
          with:
            name: cypress-screenshots
            path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
        - uses: actions/upload-artifact@v2
          if: always()
          with:
            name: cypress-videos
            path: cypress/videos